name: Test and deploy
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  avoid_reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_tocken: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm i
      - name: Run Coverage
        run: npm run test:coverage
      - name: Save coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    needs: test
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "Vue-Malaga"
          reponame: "Rick-And-Morty"
          token: ${{ secrets.GITHUB_TOKEN }}
    
  sonarcloud:
      name: SonarCloud
      runs-on: ubuntu-latest
      if: ${{ always() }}
      needs: test
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Get coverage results
          uses: actions/download-artifact@v2
          with:
            name: coverage
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
